[package]
name = "zealotd"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
rusqlite = {version = "*", features = ["bundled"]}
once_cell = "1"
directories = "5"
serde = "*"
serde_json = "*"
time = {version = "*", features = ["serde"]}